# Generated by Django 5.0.7 on 2024-07-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('Mobile App Development', 'Mobile App Development')], max_length=50)),
                ('languages_used', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C++', 'C++')], max_length=50)),
                ('duration', models.IntegerField(help_text='Duration in days')),
            ],
        ),
    ]
